# Generated by Django 3.0.2 on 2024-01-05 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='ID',
            new_name='SID',
        ),
    ]
