# Generated by Django 3.0.2 on 2024-01-05 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20240105_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='SID',
            new_name='ID',
        ),
    ]
