# Generated by Django 3.0.2 on 2024-01-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20240105_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='ID',
        ),
        migrations.AddField(
            model_name='students',
            name='RollNo',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
