# Generated by Django 3.0.2 on 2024-01-05 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20240105_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='RollNo',
        ),
    ]
