# Generated by Django 3.0.2 on 2024-01-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_students_rollno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Course', models.CharField(max_length=20)),
                ('Location', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
