# Generated by Django 5.0.1 on 2024-01-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseId', models.IntegerField()),
                ('CourseName', models.CharField(max_length=20)),
                ('CourseFees', models.IntegerField()),
                ('CourseDuration', models.IntegerField()),
            ],
        ),
    ]
