# Generated by Django 3.0.2 on 2024-01-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eid', models.IntegerField()),
                ('Name', models.CharField(max_length=20)),
                ('Salary', models.IntegerField()),
                ('Location', models.CharField(max_length=20)),
                ('Position', models.CharField(max_length=20)),
            ],
        ),
    ]
