# Generated by Django 3.0.2 on 2024-01-05 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20240105_0026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emp',
            new_name='Students',
        ),
    ]
