# Generated by Django 3.0.2 on 2024-01-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_ID', models.IntegerField()),
                ('Course_Name', models.CharField(max_length=20)),
                ('Course_Fees', models.IntegerField()),
                ('Course_Duration', models.CharField(max_length=20)),
            ],
        ),
    ]
